stages:
  - build
  - publish

gradle-build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG == null
  image: gradle:7-jdk16
  script: gradle build

nexus-deploy:
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG
  image: gradle:7-jdk16
  script: gradle -PsnapshotRepo="$NEXUS_SNAPSHOTS" -PreleaseRepo="$NEXUS_RELEASES" -PdeployUser="$NEXUS_DEPLOY_USER" -PdeployPassword="$NEXUS_DEPLOY_PASSWORD" publish
