stages:
  - publish

nexus-deploy:
  stage: publish
  image: gradle:7-jdk16
  script: gradle -PsnapshotRepo="$NEXUS_SNAPSHOTS" -PreleaseRepo="$NEXUS_RELEASES" -PdeployUser="$NEXUS_DEPLOY_USER" -PdeployPassword="$NEXUS_DEPLOY_PASSWORD" publish
